version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.0.50:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.50:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  admin-service:
    container_name: admin-service
    build: ./admin-service
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    depends_on:
      - kafka

  producer-service:
    container_name: producer-service
    build: ./producer-service
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app
    depends_on:
      - kafka

  consumer-service:
    container_name: consumer-service
    build: ./consumer-service
    ports:
      - "8003:8003"
    volumes:
      - ./app:/app
    depends_on:
      - kafka
